language: julia
os:
  - osx
  - linux
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

codecov: true

jobs:
  include:
    - stage: Documentation
      julia: 1.2
      script: julia --project=docs -e '
        using Pkg;
        Pkg.develop(PackageSpec(path=pwd()));
        Pkg.instantiate();
        include("docs/make.jl");'
      after_success: skip
