name = "SkyCoords"
uuid = "fc659fc5-75a3-5475-a2ea-3da92c065361"
authors = "Kyle Barbary, Mosé Giordano, and contributors"
version = "0.7.0"

[deps]
AstroAngles = "5c4adb95-c1fc-4c53-b4ea-2a94080c53d2"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
AstroAngles = "0.1"
StaticArrays = "0.8, 0.9, 1"
julia = "1.3"
